function runWorkoutLoggingHistoryTests(){
  const tests=[];function record(id,pass,details){tests.push({id:id,status:pass?"PASS":"FAIL",details:pass?{}:details||{}});}
  let seq=0;
  function env(plan){const rows=[],captures=[],keys={};const deps={uuid:function(){seq+=1;return "id"+seq;},time_zone:function(){return "Europe/Moscow";},format_date:function(d){return new Date(new Date(d).getTime()+3*3600000).toISOString().slice(0,10);},read_log:function(){return {headers:WORKOUT_LOG_SCHEMA.slice(),rows:rows.slice()};},append_atomic:function(batch){const batchKeys=batch.map(function(r){return String(r[WORKOUT_LOG_SCHEMA.indexOf("IDEMPOTENCY_KEY")]);});if(batchKeys.some(function(k){return keys[k];}))return {ok:true,code:"IDEMPOTENT_REPLAY",rows_written:0,idempotent_replay:true};batchKeys.forEach(function(k){keys[k]=true;});Array.prototype.push.apply(rows,batch);return {ok:true,rows_written:batch.length};},load_plan:function(){return plan===null?{ok:true,configured:false,sessions_by_weekday:{}}:{ok:true,configured:true,sessions_by_weekday:{SUNDAY:plan}};},create_capture:function(payload,meta){captures.push({capture:{row_number:captures.length+2,user_id:meta.user_id,chat_id:meta.chat_id,capture_id:payload.capture_id},payload:payload});return {ok:true,created:true};},find_capture:function(){return captures.length?captures[captures.length-1]:{ok:false};},cancel_capture:function(){return {ok:true,code:"CANCELLED"};},finalize_capture:function(){return true;}};return {rows:rows,captures:captures,deps:deps};}
  const plan={stable_session_identity:"back",display_name:"спина",exercises:[{stable_exercise_identity:"barbell_row",display_name:"Тяга штанги",order:1},{stable_exercise_identity:"pulldown",display_name:"Тяга верхнего блока",order:2}]};
  const now=new Date("2026-08-30T12:00:00Z");function call(e,intent,id){return executeWorkoutIntent_("u1",intent,id||("u"+(seq+1)),now,{dependencies:e.deps,chat_id:"c1"});}function history(e,user){return loadEffectiveWorkoutHistory_(user||"u1",{dependencies:e.deps});}
  let e=env(plan),r=call(e,{intent:"START",session_hint:""},"start1"),h=history(e);record("WLH-01_EXPLICIT_START_PLAN",r.ok&&h.sessions.length===1,r);record("WLH-02_IN_PROGRESS",h.sessions[0].status==="IN_PROGRESS",h);record("WLH-03_PLAN_LINKED",h.sessions[0].mode==="PLAN_LINKED",h);record("WLH-04_SESSION_KEY",h.sessions[0].session_key==="back",h);
  r=call(e,{intent:"START",session_hint:""},"start2");record("WLH-05_SECOND_OPEN_REJECTED",r.code==="UNFINISHED_SESSION",r);record("WLH-06_DUPLICATE_START_NO_SECOND",history(e).sessions.length===1,history(e));
  r=call(e,{intent:"SETS",exercise_text:"Тяга штанги",count:1,load:170,unit:"kg",reps:5},"set1");h=history(e);record("WLH-07_FIRST_SET",r.ok&&h.sessions[0].sets.length===1,r);record("WLH-08_PLANNED_EXERCISE_KEY",h.sessions[0].sets[0].exercise_key==="barbell_row",h);record("WLH-09_ACTUAL_DIFFERS_PLAN",h.sessions[0].sets[0].load===170,h);record("WLH-10_SET_INDEX_ONE",h.sessions[0].sets[0].set_index===1,h);
  r=call(e,{intent:"SETS",exercise_text:"",count:1,load:175,unit:"kg",reps:4},"set2");h=history(e);record("WLH-11_ACTIVE_EXERCISE",r.ok&&h.sessions[0].sets.length===2,r);record("WLH-12_SET_INDEX_TWO",h.sessions[0].sets[1].set_index===2,h);record("WLH-13_SNAPSHOT_NAME",h.sessions[0].sets[1].exercise_name==="Тяга штанги",h);
  r=call(e,{intent:"SETS",exercise_text:"Тяга верхнего блока",count:3,load:50,unit:"kg",reps:10},"multi1");h=history(e);record("WLH-14_MULTI_THREE",r.ok&&h.sessions[0].sets.length===5,r);record("WLH-15_MULTI_INDICES",h.sessions[0].sets.filter(function(s){return s.exercise_key==="pulldown";}).map(function(s){return s.set_index;}).join(",")==="1,2,3",h);const before=e.rows.length;r=call(e,{intent:"SETS",exercise_text:"Тяга верхнего блока",count:3,load:50,unit:"kg",reps:10},"multi1");record("WLH-16_MULTI_REPLAY",r.ok&&e.rows.length===before,r);
  record("WLH-17_BAD_REPS",!call(e,{intent:"SETS",exercise_text:"",count:1,load:50,unit:"kg",reps:0},"bad1").ok,{});record("WLH-18_BAD_LOAD",!call(e,{intent:"SETS",exercise_text:"",count:1,load:"bad",unit:"kg",reps:5},"bad2").ok,{});record("WLH-19_BAD_UNIT",!call(e,{intent:"SETS",exercise_text:"",count:1,load:50,unit:"lb",reps:5},"bad3").ok,{});record("WLH-20_BAD_MULTI_ZERO_WRITE",e.rows.length===before,{});
  r=call(e,{intent:"CORRECT",exercise_text:"Тяга штанги",load:180,unit:"kg",reps:3},"corr1");record("WLH-21_CORRECTION_PENDING",r.code==="CONFIRMATION_REQUESTED"&&e.captures.length===1,r);record("WLH-22_CORRECTION_PREWRITE_ZERO",history(e).sessions[0].sets.filter(function(s){return s.exercise_key==="barbell_row";})[1].load===175,history(e));let pending=e.captures[0],confirmed=executeWorkoutPendingAction_(pending,"u1",now,e.deps);h=history(e);record("WLH-23_CORRECTION_CONFIRMED",confirmed.ok,confirmed);record("WLH-24_CORRECT_EFFECTIVE_ONCE",h.sessions[0].sets.length===5,h);record("WLH-25_CORRECT_VALUE",h.sessions[0].sets.filter(function(s){return s.exercise_key==="barbell_row";})[1].load===180,h);record("WLH-26_CORRECT_REVISION",h.sessions[0].sets.filter(function(s){return s.exercise_key==="barbell_row";})[1].revision===2,h);record("WLH-27_STALE_CORRECTION",executeWorkoutPendingAction_(pending,"u1",now,e.deps).code==="STALE_TARGET",{});
  r=call(e,{intent:"DELETE",exercise_text:"Тяга верхнего блока"},"del1");record("WLH-28_DELETE_PENDING",r.code==="CONFIRMATION_REQUESTED",r);const preDelete=history(e).sessions[0].sets.length;confirmed=executeWorkoutPendingAction_(e.captures[e.captures.length-1],"u1",now,e.deps);h=history(e);record("WLH-29_DELETE_CONFIRMED",confirmed.ok,confirmed);record("WLH-30_DELETE_EFFECTIVE",h.sessions[0].sets.length===preDelete-1,h);record("WLH-31_DELETE_NO_RENUMBER",h.sessions[0].sets.filter(function(s){return s.exercise_key==="pulldown";}).map(function(s){return s.set_index;}).join(",")==="1,2",h);
  r=call(e,{intent:"SKIP",exercise_text:"Тяга верхнего блока"},"skip1");record("WLH-32_SKIP_PENDING",r.code==="CONFIRMATION_REQUESTED",r);record("WLH-33_SKIP_PREWRITE_ZERO",history(e).sessions[0].skipped.length===0,{});confirmed=executeWorkoutPendingAction_(e.captures[e.captures.length-1],"u1",now,e.deps);h=history(e);record("WLH-34_SKIP_DISTINCT",confirmed.ok&&h.sessions[0].skipped.length===1,confirmed);record("WLH-35_SKIP_NOT_SET",h.sessions[0].sets.length===4,h);
  r=call(e,{intent:"FINISH"},"finish1");h=history(e);record("WLH-36_FINISH",r.ok&&h.sessions[0].status==="COMPLETED",r);record("WLH-37_COMPLETED_AT",h.sessions[0].completed_at instanceof Date,h);record("WLH-38_SET_AFTER_COMPLETION",call(e,{intent:"SETS",exercise_text:"",count:1,load:50,unit:"kg",reps:5},"late").code!=="SETS_LOGGED",{});record("WLH-39_SUMMARY_NO_TONNAGE",!/тоннаж|pr|рекорд/i.test(r.message),r);
  let ad=env(null);r=call(ad,{intent:"SETS",exercise_text:"присед",count:1,load:100,unit:"kg",reps:5},"adhoc1");h=history(ad);record("WLH-40_ADHOC_AUTOSTART",r.ok&&h.sessions[0].mode==="AD_HOC",r);record("WLH-41_ADHOC_IDENTITY",h.sessions[0].sets[0].exercise_key==="squat",h);record("WLH-42_ARBITRARY_REJECT",!call(env(null),{intent:"SETS",exercise_text:"супер движение",count:1,load:10,unit:"kg",reps:5},"x").ok,{});record("WLH-43_EXERCISELESS_NO_CONTEXT",!call(env(null),{intent:"SETS",exercise_text:"",count:1,load:10,unit:"kg",reps:5},"x2").ok,{});record("WLH-44_EXPLICIT_ADHOC_KNOWN",call(env(null),{intent:"START",session_hint:"спина"},"a1").ok,{});record("WLH-45_EXPLICIT_ADHOC_ARBITRARY",!call(env(null),{intent:"START",session_hint:"магия"},"a2").ok,{});
  const completedHistory=workoutHistoryIntentResult_("u1",{intent:"HISTORY_LAST"},now,{dependencies:e.deps});record("WLH-46_LAST_COMPLETED",completedHistory.ok&&/спина/.test(completedHistory.message),completedHistory);const todayHistory=workoutHistoryIntentResult_("u1",{intent:"HISTORY_TODAY"},now,{dependencies:e.deps});record("WLH-47_TODAY_HISTORY",todayHistory.ok&&/Тяга штанги/.test(todayHistory.message),todayHistory);const exerciseHistory=workoutHistoryIntentResult_("u1",{intent:"HISTORY_EXERCISE",exercise_text:"тяга штанги"},now,{dependencies:e.deps});record("WLH-48_EXERCISE_HISTORY",exerciseHistory.ok&&/180 кг × 3/.test(exerciseHistory.message),exerciseHistory);record("WLH-49_DELETED_ABSENT",!/50 кг × 10\n3\./.test(exerciseHistory.message),exerciseHistory);record("WLH-50_SKIP_ABSENT_PERFORMANCE",!/Пропущено/.test(exerciseHistory.message),exerciseHistory);
  const noHistory=workoutHistoryIntentResult_("u1",{intent:"HISTORY_LAST"},now,{dependencies:env(null).deps});record("WLH-51_NO_HISTORY",noHistory.code==="NOT_FOUND",noHistory);const other=history(e,"foreign");record("WLH-52_CROSS_USER",other.sessions.length===0,other);record("WLH-53_COACH_STATE_LOSS",history(ad).sessions[0].status==="IN_PROGRESS",history(ad));record("WLH-54_STALE_REMAINS_OPEN",history(ad).sessions[0].status==="IN_PROGRESS",history(ad));record("WLH-55_NEW_WHILE_STALE_REJECT",call(ad,{intent:"START",session_hint:"ноги"},"new").code==="UNFINISHED_SESSION",{});
  const intentCases=[["начал тренировку","START"],["начал спину","START"],["закончил тренировку","FINISH"],["тяга штанги 160 на 5","SETS"],["160 × 5","SETS"],["еще 160 на 5","SETS"],["3×10 50 кг","SETS"],["3 подхода по 10 с 50 кг","SETS"],["что я сделал сегодня?","HISTORY_TODAY"],["покажи последнюю тренировку","HISTORY_LAST"],["сколько я тянул в прошлый раз?","HISTORY_EXERCISE"],["пропустил тяга верхнего блока","SKIP"]];intentCases.forEach(function(c,i){const detected=detectWorkoutLoggingHistoryIntent_(c[0]);record("WLH-"+(56+i)+"_PARSE",detected&&detected.intent===c[1],{text:c[0],detected:detected});});
  const startRow=WORKOUT_LOG_SCHEMA.indexOf("PERFORMED_AT"),mid=env(null);mid.rows.push(workoutLifecycleRow_({user_id:"u1",telegram_id:"u1",session_id:"mid",session_mode:"AD_HOC",session_name:"спина",event_type:"SESSION_START",event_id:"m1",idempotency_key:"m1",performed_at:"2026-08-29T20:50:00Z",session_status:"IN_PROGRESS",local_date:"2026-08-29"}));mid.rows.push(workoutLifecycleRow_({user_id:"u1",telegram_id:"u1",session_id:"mid",session_mode:"AD_HOC",session_name:"спина",event_type:"SESSION_COMPLETE",event_id:"m2",idempotency_key:"m2",performed_at:"2026-08-29T21:30:00Z",session_status:"COMPLETED",completed_at:"2026-08-29T21:30:00Z",local_date:"2026-08-29"}));const mh=history(mid);record("WLH-68_MIDNIGHT_START_DATE",workoutActualDate_(mh.sessions[0].started_at,mid.deps)==="2026-08-29",mh);
  const routeCases=[["что у меня сегодня по тренировке",null],["что я ел сегодня",null],["сколько осталось калорий",null],["удали последний банан",null],["исправь последний банан на 200 г",null],["мой вес 117 кг",null],["банан 200 г",null]];routeCases.forEach(function(c,i){record("WLH-"+(69+i)+"_ROUTING",detectWorkoutLoggingHistoryIntent_(c[0])===c[1],{text:c[0]});});record("WLH-76_GROQ_ZERO",[completedHistory,todayHistory,exerciseHistory].every(function(x){return x.groq_calls===0}),{});record("WLH-77_PRIVACY",!/SESSION_ID|SET_ID|LOGICAL|EXERCISE_KEY|SCHEMA|SOURCE|u1|id\d/.test(completedHistory.message+todayHistory.message+exerciseHistory.message),{});
  const decimal=env(plan);call(decimal,{intent:"START",session_hint:""},"decimal-start");call(decimal,{intent:"SETS",exercise_text:"Тяга штанги",count:1,load:155,unit:"kg",reps:5},"decimal-base");
  const exactDot=detectWorkoutLoggingHistoryIntent_("исправь последний Тяга штанги на 157.5 кг на 4");record("WLH-78_CORRECT_DOT_PARSE",exactDot&&exactDot.intent==="CORRECT"&&exactDot.exercise_text==="тяга штанги"&&exactDot.load==="157.5"&&exactDot.unit==="kg"&&exactDot.reps==="4",exactDot);
  const dotRows=decimal.rows.length,dotResult=call(decimal,exactDot,"decimal-correct-dot");record("WLH-79_CORRECT_DOT_PROPOSAL",dotResult.code==="CONFIRMATION_REQUESTED"&&decimal.captures.length===1,dotResult);record("WLH-80_CORRECT_DOT_FROZEN",decimal.captures[0].payload.frozen.new_load===157.5&&decimal.captures[0].payload.frozen.new_reps===4,decimal.captures[0]);record("WLH-81_CORRECT_DOT_PREWRITE_ZERO",decimal.rows.length===dotRows,{before:dotRows,after:decimal.rows.length});
  const exactComma=detectWorkoutLoggingHistoryIntent_("исправь последний Тяга штанги на 157,5 кг на 4"),commaRows=decimal.rows.length,commaResult=call(decimal,exactComma,"decimal-correct-comma");record("WLH-82_CORRECT_COMMA_PARSE",exactComma&&exactComma.load==="157,5"&&exactComma.unit==="kg",exactComma);record("WLH-83_CORRECT_COMMA_PROPOSAL",commaResult.code==="CONFIRMATION_REQUESTED"&&decimal.captures[1].payload.frozen.new_load===157.5,commaResult);record("WLH-84_CORRECT_COMMA_PREWRITE_ZERO",decimal.rows.length===commaRows,{before:commaRows,after:decimal.rows.length});
  [["157..5","4"],["157,5,5","4"],["-157.5","4"],["0","4"],["157.5","0"],["157.5","4.5"],["157.5","4,5"]].forEach(function(parts,i){const beforeRows=decimal.rows.length,text="исправь последний Тяга штанги на "+parts[0]+" кг на "+parts[1],parsed=detectWorkoutLoggingHistoryIntent_(text),result=routeWorkoutLoggingHistory_({update_id:"bad-decimal-"+i,message:{text:text,from:{id:"u1"},chat:{id:"c1"}}},{now:now,dependencies:decimal.deps});record("WLH-"+(85+i)+"_MALFORMED_REJECT",result.handled===true&&result.ok===false&&decimal.rows.length===beforeRows,{text:text,parsed:parsed,result:result});});
  const singleDot=detectWorkoutLoggingHistoryIntent_("Тяга штанги 157.5 на 4"),singleComma=detectWorkoutLoggingHistoryIntent_("Тяга штанги 157,5 на 4");record("WLH-92_SINGLE_DOT_PARSE",singleDot&&workoutActualNumber_(singleDot.load)===157.5&&workoutActualInteger_(singleDot.reps)===4,singleDot);record("WLH-93_SINGLE_COMMA_PARSE",singleComma&&workoutActualNumber_(singleComma.load)===157.5&&workoutActualInteger_(singleComma.reps)===4,singleComma);
  const multiDot=detectWorkoutLoggingHistoryIntent_("Тяга верхнего блока 3×10 52.5 кг"),multiComma=detectWorkoutLoggingHistoryIntent_("Тяга верхнего блока 3×10 52,5 кг");record("WLH-94_MULTI_DOT_PARSE",multiDot&&Number(multiDot.count)===3&&workoutActualNumber_(multiDot.load)===52.5,multiDot);record("WLH-95_MULTI_COMMA_PARSE",multiComma&&Number(multiComma.count)===3&&workoutActualNumber_(multiComma.load)===52.5,multiComma);
  const singleDotEnv=env(plan);call(singleDotEnv,{intent:"START",session_hint:""},"single-dot-start");const singleDotResult=call(singleDotEnv,singleDot,"single-dot");record("WLH-96_SINGLE_DOT_PERSISTED",singleDotResult.ok&&history(singleDotEnv).sessions[0].sets[0].load===157.5,singleDotResult);
  const singleCommaEnv=env(plan);call(singleCommaEnv,{intent:"START",session_hint:""},"single-comma-start");const singleCommaResult=call(singleCommaEnv,singleComma,"single-comma");record("WLH-97_SINGLE_COMMA_PERSISTED",singleCommaResult.ok&&history(singleCommaEnv).sessions[0].sets[0].load===157.5,singleCommaResult);
  const multiDotEnv=env(plan);call(multiDotEnv,{intent:"START",session_hint:""},"multi-dot-start");const multiDotResult=call(multiDotEnv,multiDot,"multi-dot"),multiDotSets=history(multiDotEnv).sessions[0].sets;record("WLH-98_MULTI_DOT_PERSISTED",multiDotResult.ok&&multiDotSets.length===3&&multiDotSets.every(function(s){return s.load===52.5;}),multiDotResult);
  const multiCommaEnv=env(plan);call(multiCommaEnv,{intent:"START",session_hint:""},"multi-comma-start");const multiCommaResult=call(multiCommaEnv,multiComma,"multi-comma"),multiCommaSets=history(multiCommaEnv).sessions[0].sets;record("WLH-99_MULTI_COMMA_PERSISTED",multiCommaResult.ok&&multiCommaSets.length===3&&multiCommaSets.every(function(s){return s.load===52.5;}),multiCommaResult);
  const explicitKg=detectWorkoutLoggingHistoryIntent_("Тяга штанги 157,5 кг на 4");record("WLH-100_SINGLE_EXPLICIT_KG_CANONICAL",explicitKg&&explicitKg.unit==="kg"&&workoutActualNumber_(explicitKg.load)===157.5,explicitKg);
  const passed=tests.filter(function(t){return t.status==="PASS";}).length;return {suite:"WORKOUT_LOGGING_HISTORY",status:passed===tests.length?"PASS":"FAIL",total:tests.length,passed:passed,failed:tests.length-passed,tests:tests,safety:{external_writes:0,telegram_calls:0,groq_calls:0,production_writes:0}};
}
